### ISSUE TITLE
Support of a different Credential Stores

### ISSUE THREAD

**Issue by lucca65** [briksoftware/plug_auth#2]
Hi!

Today `plug_auth` only supports an private agent to Store credentials. For me, the best scenario is when basic auth is checked with my configured db... there are plans to allow me to Specify an `GenServer` that gives database access to my credentials?

There is another easier way to achieve this?

Thanks

**Comment by briksoftware** [comment]
Hi. This is a good idea, PR would be welcome.

**Comment by briksoftware** [comment]
I merged the PR and released the new version. I made some refactoring, please check it and see if it works fine for you (it should). I also removed the extra tests because they were basically redundant, they were only checking that the store is correctly read from the map, but this is pretty much trivial.
